"""initial schema

Revision ID: f5fcac2cfa19
Revises: 
Create Date: 2025-11-17 12:24:38.451219

"""
from typing import Sequence, Union

import geoalchemy2
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f5fcac2cfa19'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_imports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('WOAH', 'CDC', 'USDA', 'STATE_AGENCY', 'MANUAL_ENTRY', 'OTHER', name='datasource'), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=True),
    sa.Column('file_hash', sa.String(length=64), nullable=True, comment='SHA-256 hash to detect duplicate imports'),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('successful_rows', sa.Integer(), nullable=False),
    sa.Column('failed_rows', sa.Integer(), nullable=False),
    sa.Column('duplicate_rows', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('error_log', sa.Text(), nullable=True, comment='Error messages from failed imports'),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('imported_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_import_status', 'data_imports', ['status', 'created_at'], unique=False)
    op.create_index(op.f('ix_data_imports_id'), 'data_imports', ['id'], unique=False)
    op.create_table('geographic_boundaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('boundary_type', sa.String(length=50), nullable=False, comment='Type: country, state, county, custom'),
    sa.Column('code', sa.String(length=50), nullable=True, comment='FIPS code, ISO code, etc.'),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('boundary', geoalchemy2.types.Geometry(geometry_type='POLYGON', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry', nullable=False), nullable=False),
    sa.Column('centroid', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True),
    sa.Column('area_sq_km', sa.Float(), nullable=True),
    sa.Column('extra_metadata', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['geographic_boundaries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_boundary_spatial', 'geographic_boundaries', ['boundary'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_geographic_boundaries_boundary_type'), 'geographic_boundaries', ['boundary_type'], unique=False)
    op.create_index(op.f('ix_geographic_boundaries_code'), 'geographic_boundaries', ['code'], unique=False)
    op.create_index(op.f('ix_geographic_boundaries_id'), 'geographic_boundaries', ['id'], unique=False)
    op.create_table('h5n1_cases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True, comment='ID from external data source (WOAH, CDC, etc.)'),
    sa.Column('case_date', sa.DateTime(), nullable=False, comment='Date when case was reported/detected'),
    sa.Column('report_date', sa.DateTime(), nullable=True, comment='Date when case was officially reported'),
    sa.Column('status', sa.Enum('SUSPECTED', 'CONFIRMED', 'RESOLVED', 'UNDER_INVESTIGATION', name='casestatus'), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('animal_category', sa.Enum('POULTRY', 'DAIRY_CATTLE', 'WILD_BIRD', 'WILD_MAMMAL', 'DOMESTIC_MAMMAL', 'OTHER', name='animalcategory'), nullable=False, comment='WOAH animal category'),
    sa.Column('animal_species', sa.String(length=255), nullable=True, comment="Specific species affected (e.g., 'Chicken', 'Holstein cow')"),
    sa.Column('animals_affected', sa.Integer(), nullable=True, comment='Number of animals affected'),
    sa.Column('animals_dead', sa.Integer(), nullable=True, comment='Number of animals deceased'),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('county', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('location_name', sa.String(length=255), nullable=True, comment='Farm name, facility name, etc.'),
    sa.Column('location', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, dimension=2, spatial_index=False, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True, comment='Geographic coordinates (longitude, latitude)'),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('data_source', sa.Enum('WOAH', 'CDC', 'USDA', 'STATE_AGENCY', 'MANUAL_ENTRY', 'OTHER', name='datasource'), nullable=False),
    sa.Column('source_url', sa.Text(), nullable=True, comment='URL to original report/data'),
    sa.Column('description', sa.Text(), nullable=True, comment='Additional case details and notes'),
    sa.Column('control_measures', sa.Text(), nullable=True, comment='Control measures taken'),
    sa.Column('extra_metadata', sa.JSON(), nullable=True, comment='Additional structured metadata'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_case_date_status', 'h5n1_cases', ['case_date', 'status'], unique=False)
    op.create_index('idx_location_category', 'h5n1_cases', ['country', 'animal_category'], unique=False)
    op.create_index('idx_severity_date', 'h5n1_cases', ['severity', 'case_date'], unique=False)
    op.create_index('idx_spatial', 'h5n1_cases', ['location'], unique=False, postgresql_using='gist')
    op.create_index(op.f('ix_h5n1_cases_animal_category'), 'h5n1_cases', ['animal_category'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_case_date'), 'h5n1_cases', ['case_date'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_country'), 'h5n1_cases', ['country'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_county'), 'h5n1_cases', ['county'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_data_source'), 'h5n1_cases', ['data_source'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_external_id'), 'h5n1_cases', ['external_id'], unique=True)
    op.create_index(op.f('ix_h5n1_cases_id'), 'h5n1_cases', ['id'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_is_deleted'), 'h5n1_cases', ['is_deleted'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_severity'), 'h5n1_cases', ['severity'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_state_province'), 'h5n1_cases', ['state_province'], unique=False)
    op.create_index(op.f('ix_h5n1_cases_status'), 'h5n1_cases', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('organization', sa.String(length=255), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('failed_login_attempts', sa.Integer(), nullable=True),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_type', sa.Enum('NEW_OUTBREAK', 'CLUSTER_DETECTED', 'SEVERITY_INCREASE', 'CROSS_SPECIES', 'GEOGRAPHIC_SPREAD', 'THRESHOLD_EXCEEDED', name='alerttype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='severity'), nullable=False),
    sa.Column('case_id', sa.Integer(), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=True),
    sa.Column('state_province', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['h5n1_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_active_alerts', 'alerts', ['is_active', 'created_at'], unique=False)
    op.create_index(op.f('ix_alerts_alert_type'), 'alerts', ['alert_type'], unique=False)
    op.create_index(op.f('ix_alerts_id'), 'alerts', ['id'], unique=False)
    op.create_index(op.f('ix_alerts_is_active'), 'alerts', ['is_active'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_is_active'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_alert_type'), table_name='alerts')
    op.drop_index('idx_active_alerts', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_h5n1_cases_status'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_state_province'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_severity'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_is_deleted'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_id'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_external_id'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_data_source'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_county'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_country'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_case_date'), table_name='h5n1_cases')
    op.drop_index(op.f('ix_h5n1_cases_animal_category'), table_name='h5n1_cases')
    op.drop_index('idx_spatial', table_name='h5n1_cases', postgresql_using='gist')
    op.drop_index('idx_severity_date', table_name='h5n1_cases')
    op.drop_index('idx_location_category', table_name='h5n1_cases')
    op.drop_index('idx_case_date_status', table_name='h5n1_cases')
    op.drop_table('h5n1_cases')
    op.drop_index(op.f('ix_geographic_boundaries_id'), table_name='geographic_boundaries')
    op.drop_index(op.f('ix_geographic_boundaries_code'), table_name='geographic_boundaries')
    op.drop_index(op.f('ix_geographic_boundaries_boundary_type'), table_name='geographic_boundaries')
    op.drop_index('idx_boundary_spatial', table_name='geographic_boundaries', postgresql_using='gist')
    op.drop_table('geographic_boundaries')
    op.drop_index(op.f('ix_data_imports_id'), table_name='data_imports')
    op.drop_index('idx_import_status', table_name='data_imports')
    op.drop_table('data_imports')
    # ### end Alembic commands ###
